openapi: 3.0.0
info:
  description: "CDAF Event Exposure Service.  \nÂ© 2023, 3GPP Organizational Partners\
    \ (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
  title: Ncdaf_EventExposure
  version: 1.2.3
externalDocs:
  description: 3GPP TS 29.518 V17.10.0; 5G System; Access and Mobility Management
    Services
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
servers:
- url: "{apiRoot}/ncdaf-evts/v1"
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
security:
- {}
- oAuth2ClientCredentials:
  - ncdaf-evts
paths:
  /subscriptions:
    post:
      callbacks:
        onEventReport:
          '{$request.body#/subscription/eventNotifyUri}':
            post:
              operationId: onEventReport_Post
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CdafEventNotification'
                required: true
              responses:
                "204":
                  description: Successful acknowledgement
                default:
                  description: Unexpected error
              summary: Event Notificaiton Delivery
              x-callback-request: true
        onSubscriptionIdChangeEvtReport:
          '{$request.body#/subscription/subsChangeNotifyUri}':
            post:
              operationId: onSubscriptionIdChangeEvtReport_Post
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CdafEventNotification'
                required: true
              responses:
                "204":
                  description: Successful acknowledgement
                default:
                  description: Unexpected error
              summary: Event Notificaiton Delivery For Subscription Id Change
              x-callback-request: true
      operationId: CreateSubscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CdafCreateEventSubscription'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CdafCreatedEventSubscription'
          description: Subsription Created
          headers:
            Location:
              description: "Contains the URI of the newly created resource, according\
                \ to the structure: {apiRoot}/ncdaf-evts/<apiVersion>/subscriptions/{subscriptionId}"
              explode: false
              required: true
              schema:
                type: string
              style: simple
        default:
          description: Unexpected error
      summary: Ncdaf_EventExposure Subscribe service Operation
      tags:
      - Subscriptions collection (Collection)
  /subscriptions/{subscriptionId}:
    delete:
      operationId: DeleteSubscription
      parameters:
      - description: Unique ID of the subscription to be deleted
        explode: false
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Subsription deleted successfully
        default:
          description: Unexpected error
      summary: Ncdaf_EventExposure Unsubscribe service Operation
      tags:
      - Individual subscription (Document)
    patch:
      operationId: ModifySubscription
      parameters:
      - description: Unique ID of the subscription to be modified
        explode: false
        in: path
        name: subscriptionId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ModifySubscription_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CdafUpdatedEventSubscription'
          description: Subsription modified successfully
        default:
          description: Unexpected error
      summary: Ncdaf_EventExposure Subscribe Modify service Operation
      tags:
      - Individual subscription (Document)
components:
  schemas:
    CdafEventSubscription:
      description: Represents an individual event subscription resource on CDAF
      example:
        eventNotifyUri: eventNotifyUri
        eventList:
        - maxResponseTime: 6
          minInterval: 1
          nextReport: 2000-01-23T04:56:07.000+00:00
          nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
          type: null
          maxReports: 0
        - maxResponseTime: 6
          minInterval: 1
          nextReport: 2000-01-23T04:56:07.000+00:00
          nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
          type: null
          maxReports: 0
        options:
          trigger: null
          expiry: 2000-01-23T04:56:07.000+00:00
          maxReports: 5
          repPeriod: 5
          sampRatio: 23
      properties:
        eventList:
          items:
            $ref: '#/components/schemas/CdafEvent'
          minItems: 1
          type: array
        eventNotifyUri:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        options:
          $ref: '#/components/schemas/CdafEventMode'
      required:
      - eventList
      - eventNotifyUri
      type: object
    CdafEvent:
      description: Describes an event to be subscribed
      example:
        maxResponseTime: 6
        minInterval: 1
        nextReport: 2000-01-23T04:56:07.000+00:00
        nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
        type: null
        maxReports: 0
      properties:
        type:
          $ref: '#/components/schemas/CdafEventType'
        maxReports:
          type: integer
        maxResponseTime:
          description: indicating a time in seconds.
          type: integer
        minInterval:
          description: indicating a time in seconds.
          type: integer
        nextReport:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        nextPeriodicReportTime:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
      required:
      - type
      type: object
    CdafEventNotification:
      description: Data within a CADF Event Notification request
      example:
        eventSubsSyncInfo:
          subscriptionList:
          - subId: subId
            oldSubId: oldSubId
          - subId: subId
            oldSubId: oldSubId
        reportList:
        - timeStamp: 2000-01-23T04:56:07.000+00:00
          path: path
          state:
            remainDuration: 9
            active: true
            remainReports: 7
          type: null
          subscriptionId: subscriptionId
        - timeStamp: 2000-01-23T04:56:07.000+00:00
          path: path
          state:
            remainDuration: 9
            active: true
            remainReports: 7
          type: null
          subscriptionId: subscriptionId
      properties:
        reportList:
          items:
            $ref: '#/components/schemas/CdafEventReport'
          minItems: 1
          type: array
        eventSubsSyncInfo:
          $ref: '#/components/schemas/CdafEventSubsSyncInfo'
      type: object
    CdafEventReport:
      description: Represents a report triggered by a subscribed event type
      example:
        timeStamp: 2000-01-23T04:56:07.000+00:00
        path: path
        state:
          remainDuration: 9
          active: true
          remainReports: 7
        type: null
        subscriptionId: subscriptionId
      properties:
        type:
          $ref: '#/components/schemas/CdafEventType'
        state:
          $ref: '#/components/schemas/CdafEventState'
        timeStamp:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        subscriptionId:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        path:
          type: string
      required:
      - state
      - timeStamp
      - type
      type: object
    CdafEventMode:
      description: Describes how the reports shall be generated by a subscribed event
      example:
        trigger: null
        expiry: 2000-01-23T04:56:07.000+00:00
        maxReports: 5
        repPeriod: 5
        sampRatio: 23
      properties:
        trigger:
          $ref: '#/components/schemas/CdafEventTrigger'
        maxReports:
          type: integer
        expiry:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        repPeriod:
          description: indicating a time in seconds.
          type: integer
        sampRatio:
          description: "Unsigned integer indicating Sampling Ratio (see clauses 4.15.1\
            \ of 3GPP TS 23.502), expressed in percent. \n"
          maximum: 100
          minimum: 1
          type: integer
      required:
      - trigger
      type: object
    CdafEventState:
      description: Represents the state of a subscribed event
      example:
        remainDuration: 9
        active: true
        remainReports: 7
      properties:
        active:
          type: boolean
        remainReports:
          type: integer
        remainDuration:
          description: indicating a time in seconds.
          type: integer
      required:
      - active
      type: object
    CdafCreateEventSubscription:
      description: Data within a create CDAF event subscription request
      example:
        subscription:
          eventNotifyUri: eventNotifyUri
          eventList:
          - maxResponseTime: 6
            minInterval: 1
            nextReport: 2000-01-23T04:56:07.000+00:00
            nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
            type: null
            maxReports: 0
          - maxResponseTime: 6
            minInterval: 1
            nextReport: 2000-01-23T04:56:07.000+00:00
            nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
            type: null
            maxReports: 0
          options:
            trigger: null
            expiry: 2000-01-23T04:56:07.000+00:00
            maxReports: 5
            repPeriod: 5
            sampRatio: 23
      properties:
        subscription:
          $ref: '#/components/schemas/CdafEventSubscription'
      required:
      - subscription
      type: object
    CdafCreatedEventSubscription:
      description: Data within a create CDAF event subscription response
      example:
        reportList:
        - timeStamp: 2000-01-23T04:56:07.000+00:00
          path: path
          state:
            remainDuration: 9
            active: true
            remainReports: 7
          type: null
          subscriptionId: subscriptionId
        - timeStamp: 2000-01-23T04:56:07.000+00:00
          path: path
          state:
            remainDuration: 9
            active: true
            remainReports: 7
          type: null
          subscriptionId: subscriptionId
        subscription:
          eventNotifyUri: eventNotifyUri
          eventList:
          - maxResponseTime: 6
            minInterval: 1
            nextReport: 2000-01-23T04:56:07.000+00:00
            nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
            type: null
            maxReports: 0
          - maxResponseTime: 6
            minInterval: 1
            nextReport: 2000-01-23T04:56:07.000+00:00
            nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
            type: null
            maxReports: 0
          options:
            trigger: null
            expiry: 2000-01-23T04:56:07.000+00:00
            maxReports: 5
            repPeriod: 5
            sampRatio: 23
        subscriptionId: subscriptionId
      properties:
        subscription:
          $ref: '#/components/schemas/CdafEventSubscription'
        subscriptionId:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        reportList:
          items:
            $ref: '#/components/schemas/CdafEventReport'
          minItems: 1
          type: array
      required:
      - subscription
      - subscriptionId
      type: object
    CdafUpdateEventSubscriptionItem:
      description: Document describing the modification(s) to an CDAF Event Subscription
      properties:
        op:
          enum:
          - add
          - remove
          - replace
          type: string
        path:
          pattern: "^\\/eventList\\/-|(\\/eventList\\/0|\\/eventList\\/[1-9][0-9]*){1}(\\\
            /presenceInfoList\\/0|\\/presenceInfoList\\/[1-9][0-9]*)?|\\/excludeSupiList|\\\
            /excludeGpsiList|\\/includeSupiList|\\/includeGpsiList$"
          type: string
        value:
          $ref: '#/components/schemas/CdafEvent'
      required:
      - op
      type: object
    CdafUpdatedEventSubscription:
      description: Represents a successful update on an CDAF Event Subscription
      example:
        reportList:
        - timeStamp: 2000-01-23T04:56:07.000+00:00
          path: path
          state:
            remainDuration: 9
            active: true
            remainReports: 7
          type: null
          subscriptionId: subscriptionId
        - timeStamp: 2000-01-23T04:56:07.000+00:00
          path: path
          state:
            remainDuration: 9
            active: true
            remainReports: 7
          type: null
          subscriptionId: subscriptionId
        subscription:
          eventNotifyUri: eventNotifyUri
          eventList:
          - maxResponseTime: 6
            minInterval: 1
            nextReport: 2000-01-23T04:56:07.000+00:00
            nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
            type: null
            maxReports: 0
          - maxResponseTime: 6
            minInterval: 1
            nextReport: 2000-01-23T04:56:07.000+00:00
            nextPeriodicReportTime: 2000-01-23T04:56:07.000+00:00
            type: null
            maxReports: 0
          options:
            trigger: null
            expiry: 2000-01-23T04:56:07.000+00:00
            maxReports: 5
            repPeriod: 5
            sampRatio: 23
      properties:
        subscription:
          $ref: '#/components/schemas/CdafEventSubscription'
        reportList:
          items:
            $ref: '#/components/schemas/CdafEventReport'
          minItems: 1
          type: array
      required:
      - subscription
      type: object
    CdafEventSubsSyncInfo:
      description: CDAF Event Subscriptions Information for synchronization
      example:
        subscriptionList:
        - subId: subId
          oldSubId: oldSubId
        - subId: subId
          oldSubId: oldSubId
      properties:
        subscriptionList:
          items:
            $ref: '#/components/schemas/CdafEventSubscriptionInfo'
          minItems: 1
          type: array
      required:
      - subscriptionList
      type: object
    CdafEventSubscriptionInfo:
      description: Individual CDAF Event Subscription Information
      example:
        subId: subId
        oldSubId: oldSubId
      properties:
        subId:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        oldSubId:
          description: String providing an URI formatted according to RFC 3986.
          type: string
      required:
      - subId
      type: object
    CdafEventType:
      anyOf:
      - $ref: '#/components/schemas/CdafEventType_anyOf'
      - type: string
      description: Describes the supported event types of Ncadf_EventExposure Service
    CdafEventTrigger:
      anyOf:
      - $ref: '#/components/schemas/CdafEventTrigger_anyOf'
      - type: string
      description: Describes how CDAF should generate the report for the event
    ModifySubscription_request:
      oneOf:
      - items:
          $ref: '#/components/schemas/CdafUpdateEventSubscriptionItem'
        minItems: 1
        type: array
    CdafEventType_anyOf:
      enum:
      - REPORT_RESOURCE_USAGE
      type: string
    CdafEventTrigger_anyOf:
      enum:
      - ONE_TIME
      - CONTINUOUS
      - PERIODIC
      type: string
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes:
            ncdaf-evts: Access to the Ncdaf_EventExposure API
          tokenUrl: "{nrfApiRoot}/oauth2/token"
      type: oauth2
